jobs:
  build:
    strategy: { matrix: { os: [macos-latest] } }
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Ensures every later `node` is v20 / ABI 115
      - uses: volta-cli/action@v4
        with: { node-version: 20 }

      - run: |
          corepack enable
          corepack prepare pnpm@10.11.0 --activate
          pnpm install         # no --ignore-scripts !

      # Sanity-check that the native binary is present
      - run: |
          node -e "console.log('forge will use', process.version, process.versions.modules)"
          ls $(dirname $(node -e "process.stdout.write(require.resolve('macos-alias'))"))/../build/Release

      - name: Build App
        run: pnpm run make
