name: Build Matrix
on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build App on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        
      - name: Build App
        run: pnpm run make
        env:
          # Ensure the correct Node.js version is used for native modules
          npm_config_target_platform: ${{ runner.os == 'Linux' && 'linux' || (runner.os == 'macOS' && 'darwin' || 'win32') }}
