name: Build Matrix
on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build App on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build App
        run: pnpm run make
        env:
          npm_config_target_platform: ${{ runner.os == 'Linux' && 'linux' || (runner.os == 'macOS' && 'darwin' || 'win32') }}
