name: Release
on:
  release:
    types: [published]

permissions:
  contents: write # Required for GitHub publisher to upload release assets

jobs:
  # security:
  #   name: Security Checks
  #   uses: ./.github/workflows/_security-checks.yml

  # static-checks:
  #   name: Static Checks
  #   uses: ./.github/workflows/_static-checks.yml
  #   secrets: inherit

  # unit-tests:
  #   name: Unit Tests
  #   uses: ./.github/workflows/_unit-tests.yml
  #   secrets: inherit

  build-and-release:
    name: Build and Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # needs: [security, static-checks, unit-tests]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Update version from tag
        shell: bash
        run: |
          # Extract version from tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/v}
          VERSION=${VERSION#v}
          echo "Setting version to: $VERSION"

          # Update package.json version
          npm version $VERSION --no-git-tag-version --allow-same-version 
          echo "Updated package.json version to $VERSION"

          # Set SENTRY_RELEASE for build and publish step
          echo "SENTRY_RELEASE=${VERSION}" >> $GITHUB_ENV

      - name: Build and Publish to GitHub Release
        run: pnpm run publish
        env:
          # Ensure the correct Node.js version is used for native modules
          npm_config_target_platform: ${{ runner.os == 'Linux' && 'linux' || (runner.os == 'macOS' && 'darwin' || 'win32') }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
          SENTRY_RELEASE: ${{ env.SENTRY_RELEASE }}
